package pt.isel.pdm.drag.utils.data

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query

/**
 * Specifies the contract to be supported by the DAO associated to the [GameResult] entity. The
 * DAO implementation is to be automatically generated by Room build tools.
 */
@Dao
interface GameResultDao {

    @Query("SELECT * FROM rounds")
    fun loadRounds(): List<GameResult.rounds>

    @Insert(entity = GameResult.rounds::class)
    fun insertRounds(game: GameResult.rounds)
}